version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: polkadot-js/apps:master    # Required. Must be in the same fork network.
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
