// Copyright 2017-2021 @polkadot/apps authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

module.exports = typeof __dirname === 'string'
  ? __dirname.replace('/cjs', '')
  : undefined;
