apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: production-ingress-substrate-ui
  namespace: poc3-122
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "https,http"
spec:
  rules:
  - host: substrate-ui.parity.io
    http:
      paths:
      - backend:
          serviceName: production-service
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: production-ingress-substrate-ui-light
  namespace: poc3-122
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "https,http"
spec:
  rules:
  - host: substrate-ui-light.parity.io
    http:
      paths:
      - backend:
          serviceName: production-service
          servicePort: 80
