name = "polymesh-apps"
type = "webpack"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./build"
entry-point = "workers-site"

[env.staging]
name = "staging-apps"

[env.testnet]
name = "testnet-apps"

[env.mainnet]
name = "mainnet-apps"