// Copyright 2017-2022 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

import { detectPackage } from '@polkadot/util';

import others from './detectOther';
import { packageInfo } from './packageInfo';

detectPackage(packageInfo, null, others);
