// Copyright 2017-2021 @polkadot/apps authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

import { detectPackage } from '@polkadot/util';

import __dirname from './cjs/dirname';
import others from './detectOther';
import { packageInfo } from './packageInfo';

detectPackage(packageInfo, __dirname, others);
