// Copyright 2017-2022 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

import type { BN } from '@polkadot/util';

import { externalLogos } from '../ui/logos';

export default {
  chains: {
    Acala: 'acala',
    'Acala Mandala TC5': 'acala-testnet',
    'Aleph Zero': 'alephzero',
    Altair: 'altair',
    Arctic: 'arctic',
    Astar: 'astar',
    Basilisk: 'basilisk',
    Bifrost: 'bifrost-kusama',
    'Bifrost Polkadot': 'bifrost',
    Calamari: 'calamari',
    'Centrifuge Mainnet': 'centrifuge',
    ChainX: 'chainx',
    Clover: 'clv',
    'Crab-parachain': 'crab-parachain',
    Crust: 'crust',
    'Crust Collator': 'shadow',
    'Crust Maxwell': 'maxwell',
    Darwinia: 'darwinia',
    'Darwinia Crab': 'crab',
    'DataHighway Tanganika Kusama Parachain': 'datahighway',
    Dock: 'dock',
    Edgeware: 'edgeware',
    Efinity: 'efinity',
    'Encointer-parachain': 'encointer',
    Equilibrium: 'equilibrium',
    Genshiro: 'genshiro',
    HydraDX: 'hydradx',
    'Integritee Collator': 'integritee',
    Interlay: 'interlay',
    'KILT Peregrine': 'kilt-testnet',
    'KILT Spiritnet': 'spiritnet',
    Karura: 'karura',
    Khala: 'khala',
    Kintsugi: 'kintsugi',
    Kulupu: 'kulupu',
    Kusama: 'kusama',
    Litentry: 'litentry',
    Litmus: 'litmus',
    Moonbase: 'moonbase',
    Moonbeam: 'moonbeam',
    Moonriver: 'moonriver',
    'Nodle Parachain': 'nodle',
    Pangolin: 'pangolin',
    'Pangolin Parachain': 'pangolin-parachain',
    Pangoro: 'pangoro',
    Parallel: 'parallel',
    'Parallel Heiko': 'parallel-heiko',
    Phala: 'phala',
    Picasso: 'picasso',
    'Pioneer Network': 'pioneer',
    Polkadex: 'polkadex',
    Polkadot: 'polkadot',
    Polymesh: 'polymesh',
    'QUARTZ by UNIQUE': 'quartz',
    Robonomics: 'robonomics',
    Rococo: 'rococo',
    SORA: 'sora',
    Shibuya: 'shibuya',
    'Shibuya Testnet': 'shibuya',
    Shiden: 'shiden',
    Stafi: 'stafi',
    Statemine: 'statemine',
    Statemint: 'statemint',
    Subgame: 'subgame',
    'Turing Network': 'turing',
    UNIQUE: 'unique',
    Westend: 'westend',
    Zeitgeist: 'zeitgeist'
  },
  create: (chain: string, path: string, data: BN | number | string): string =>
    `https://${chain}.subscan.io/${path}/${data.toString()}`,
  isActive: true,
  logo: externalLogos.subscan as string,
  paths: {
    address: 'account',
    block: 'block',
    bounty: 'bounty',
    council: 'council',
    extrinsic: 'extrinsic',
    proposal: 'democracy_proposal',
    referendum: 'referenda',
    techcomm: 'tech',
    treasury: 'treasury',
    validator: 'validator'
  },
  url: 'https://subscan.io/'
};
