// Copyright 2017-2023 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0

import type { BN } from '@polkadot/util';
import type { ExternalDef } from './types';

import { externalSubscanPNG } from '../ui/logos/external';

export const Subscan: ExternalDef = {
  chains: {
    Acala: 'acala',
    'Acala Mandala TC5': 'acala-testnet',
    'Aleph Zero': 'alephzero',
    Altair: 'altair',
    Arctic: 'arctic',
    Astar: 'astar',
    Basilisk: 'basilisk',
    Bifrost: 'bifrost-kusama',
    'Bifrost Polkadot': 'bifrost',
    'Calamari Parachain': 'calamari',
    Centrifuge: 'centrifuge',
    ChainX: 'chainx',
    Clover: 'clv',
    'Composable Finance': 'composable',
    'Crab Parachain': 'crab-parachain',
    Crust: 'crust',
    'Crust Maxwell': 'maxwell',
    'Crust Shadow': 'shadow',
    'Dali Testnet (Rococo Relay)': 'dali',
    Darwinia: 'darwinia',
    'Darwinia Crab': 'crab',
    'Darwinia Parachain': 'darwinia-parachain',
    'DataHighway Tanganika Kusama Parachain': 'datahighway',
    Dock: 'dock',
    'Dolphin Parachain Testnet': 'dolphin',
    Edgeware: 'edgeware',
    Efinity: 'efinity',
    'Encointer on Kusama': 'encointer',
    'Equilibrium parachain': 'equilibrium',
    Genshiro: 'genshiro',
    HydraDX: 'hydradx',
    'Integritee Network (Kusama)': 'integritee',
    Interlay: 'interlay',
    'KILT Peregrine': 'kilt-testnet',
    'KILT Spiritnet': 'spiritnet',
    Karura: 'karura',
    Khala: 'khala',
    Kulupu: 'kulupu',
    Kusama: 'kusama',
    Litmus: 'litmus',
    'Mangata Kusama Mainnet': 'mangatax',
    'Mangata Public Testnet': 'mangata-testnet',
    'Moonbase Alpha': 'moonbase',
    Moonbeam: 'moonbeam',
    Moonriver: 'moonriver',
    'Nodle Parachain': 'nodle',
    Pangolin: 'pangolin',
    'Pangolin Parachain': 'pangolin-parachain',
    Pangoro: 'pangoro',
    Parallel: 'parallel',
    'Parallel Heiko': 'parallel-heiko',
    Phala: 'phala',
    Picasso: 'picasso',
    'Pioneer Network': 'pioneer',
    Polkadex: 'polkadex',
    Polkadot: 'polkadot',
    Polymesh: 'polymesh',
    'Polymesh Testnet': 'polymesh-testnet',
    'QUARTZ by UNIQUE': 'quartz',
    Robonomics: 'robonomics',
    Rockmine: 'rockmine',
    Rococo: 'rococo',
    SORA: 'sora',
    'Shibuya Testnet': 'shibuya',
    Shiden: 'shiden',
    Stafi: 'stafi',
    Statemine: 'statemine',
    Statemint: 'statemint',
    'Subspace Gemini 2a': 'subspace',
    'Turing Network': 'turing',
    UNIQUE: 'unique',
    Westend: 'westend',
    Zeitgeist: 'zeitgeist',
    kintsugi: 'kintsugi'
  },
  create: (chain: string, path: string, data: BN | number | string): string =>
    `https://${chain}.subscan.io/${path}/${data.toString()}`,
  homepage: 'https://subscan.io/',
  isActive: true,
  paths: {
    address: 'account',
    block: 'block',
    bounty: 'bounty',
    council: 'council',
    democracyProposal: 'democracy_proposal',
    democracyReferendum: 'referenda',
    extrinsic: 'extrinsic',
    techcomm: 'tech',
    tip: 'treasury_tip',
    treasury: 'treasury',
    validator: 'validator'
  },
  ui: {
    logo: externalSubscanPNG
  }
};
