name: PR

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jacogr/action-approve@master
        with:
          authors: jacogr
          labels: automerge
          token: ${{ secrets.GH_PAT_BOT }}
