name: Deployment
on:
  push:
    branches:
      - mainnet

jobs:
  cloudflare:
    name: Cloudflare workers deployment
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: yarn
    - name: Update endpoint to mainnet
      run: APP_NAME="Polymesh Mainnet" RPC_ENDPOINT="mainnet-rpc.polymesh.network" sh ./scripts/updateEndpoint.sh
    - name: Deployment to mainnet-app.polymesh.network
      run: yarn run wrangler:mainnet:publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  dummy:
    name: Dummy
    if: "contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - name: dummy
      run: |
        echo "Dummy skip step"
