name: Publish Docker Image
on:
  pull_request:
    types: [closed]
    branches:
      - 'develop'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          name: benxgao/polkadot-apps
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest, $RELEASE_VERSION'
