name: Release
on: [pull_request]

jobs:
  release-electron:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # Base64-encoded code signing certificate for macOS
          mac_certs: ${{ secrets.mac_certs }}
          # Password for decrypting `mac_certs`
          mac_certs_password: ${{ secrets.mac_certs_password }}
          # Base64-encoded code signing certificate for Windows
          windows_certs: ${{ secrets.windows_certs }}
          # Password for decrypting `windows_certs`
          windows_certs_password: ${{ secrets.windows_certs_password }}
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          build_script_name: build:release:electron
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building

  dummy:
    name: Dummy
    if: "contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: |
          echo "Dummy skip step"
