name: Deployment
on:
  push:
    branches:
      - staging

jobs:
  cloudflare:
    name: Cloudflare workers deployment
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: yarn
    - name: Update endpoint to staging
      run: APP_NAME="Polymesh Staging" RPC_HOSTNAME="staging-rpc.polymesh.live" sh ./scripts/updateEndpoint.sh
    - name: Deployment to staging-app.polymesh.live
      run: yarn run wrangler:staging:publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  dummy:
    name: Dummy
    if: "contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - name: dummy
      run: |
        echo "Dummy skip step"
