name: Deployment
on:
  push:
    branches:
      - testnet

jobs:
  cloudflare:
    name: Cloudflare workers deployment
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: yarn
    - name: Update endpoint to testnet
      run: APP_NAME="Polymesh Testnet" RPC_HOSTNAME="testnet-rpc.polymesh.live" sh ./scripts/updateEndpoint.sh
    - name: Deployment to testnet-app.polymesh.live
      run: yarn run wrangler:testnet:publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  dummy:
    name: Dummy
    if: "contains(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
    - name: dummy
      run: |
        echo "Dummy skip step"
