name: Nightly tests run
on:
  schedule:
    - cron:  '1 5 * * *'


jobs:
  alltests:
    strategy:
      matrix:
        step: ['test:all']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: ${{ matrix.step }}
      run: |
        yarn install --immutable
        yarn ${{ matrix.step }}
